steps:
- label: build systems
  commands:
  - nix-build -A nixosSystems
- label: terraform validate
  commands:
  - nix-shell --run "cd terraform; terraform init -backend=false && terraform validate"
- label: Check flake
  commands:
  - nix-build -A checks.x86_64-linux
