steps:
  - label: nix build
    command: nix-build
    agents:
      private: true

  - wait

  - label: deploy staging
    command: scripts/deploy.sh staging system
    branches:
      - staging
    agents:
      private: true

  - label: deploy production
    command: scripts/deploy.sh production system
    branches:
      - production
    agents:
      private: true

  - label: deploy blnd demo
    commands:
      - nix-build -A deploy
      - ./result/bin/deploy --repo "ssh://git@github.com/stakerdao/blend-app" --ref "${REF-demo}" Blend_Demo System
    branches:
      - blnd-demo
    agents:
      private: true
