steps:
- label: build systems
  commands:
  - nix-build -A nixosSystems
- label: terraform validate
  commands:
  - nix-shell --run "terraform init -backend=false terraform && terraform validate terraform"
- label: Check flake
  commands:
  - nix-build -A checks.x86_64-linux
